version: '3'
services:
  db:
    image: postgres:11.5
    volumes:
      - ./tmp/db:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: ./docker/rails/Dockerfile
    command: /bin/sh -c "rm -f /app/tmp/pids/server.pid && bundle exec rails s"
    volumes:
      - .:/app
      - tmp-volume:/app/tmp
    depends_on:
      - db

  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - 80:80
    volumes:
      - tmp-volume:/app/tmp
    depends_on:
      - app

volumes:
  db-volume:
  tmp-volume:
  public-volume:
